CLI: Allow users to exclude findings by tag
duo-labs/parliament pull request #149
Opened 2020-10-01 03:58 UTC by raghavkaul

To support #59, I added an option to `--exclude` certain types of parliament findings by tags. In config.yaml, the `group` argument is now a list of `tag` arguments.

The `--exclude` option _does not_ affect the `--minimum_severity` option, but I haven't checked if the `group` argumnet was being used anywhere.

2020-10-01 03:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/duo-labs/parliament?pullRequest=149) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/duo-labs/parliament?pullRequest=149) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/duo-labs/parliament?pullRequest=149) it.</sub>

2020-10-01 14:45 UTC, 0xdabbad00 requested changes

2020-10-01 14:45 UTC, 0xdabbad00 commented on tests/scripts/unit_tests.sh
> ---cover-min-percentage=75 \
I'd like to avoid dropping the minimum coverage.

2020-10-01 14:47 UTC, 0xdabbad00 commented
Thanks @raghavkaul .  I can't remember if I was using the groups for anything in Parliament or in CloudMapper (which uses Parliament).  I'll double-check and I want to avoid dropping the minimum test coverage.  Once those two things get figured out, this will be mergeable.

2020-11-16 21:53 UTC, raghavkaul commented
Sorry for the delay on this. Test coverage %age dropped because now a whole new file (cli.py) is included in the the lines-of-code calculation even though new tests were added. However, it's hard to split it up and test it, so I am trying to increase coverage where I can.

2021-11-03 21:12 UTC, 0xdabbad00 commented
Closing this due to staleness and this project mostly being on life-support now.

2021-11-03 21:12 UTC, closed without merging